spring:
  kafka:
    bootstrap-servers: localhost:9092 # Change to kafka:29092 if service is dockerized
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.user_service.dto.response.AvatarUploadedEvent" # Your local DTO package
        spring.json.use.type.headers: false # Ignores type headers sent by Media Service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: user-service
  config:
    import: optional:file:./.env[.properties]
  mongodb:
    host: localhost
    port: 27017
    database: ${MONGO_INITDB_DATABASE}
    username: ${MONGO_INITDB_ROOT_USERNAME}
    password: ${MONGO_INITDB_ROOT_PASSWORD}
    authentication-database: admin

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: ${SERVER_PORT}
