services:
  # -------------------------------------------------------------
  # USER MONGODB
  # -------------------------------------------------------------
  user-db:
    image: mongo:7.0
    container_name: mongodb_user
    restart: always
    env_file:
      - ./user-service/.env
    ports:
      - "27017:27017"
    volumes:
      - user_mongodb_data:/data/db
  media-db:
    image: mongo:7.0
    container_name: mongodb_media
    restart: always
    env_file:
      - ./media-Service/.env
    ports:
      - "27018:27017"
    volumes:
      - media_mongodb_data:/data/db
  product-db:
    image: mongo:latest
    container_name: product-service
    restart: always
    env_file:
      - ./product-service/.env
    ports:
      - "27019:27017"
    volumes:
      - product_mongodb_data:/data/db
volumes:
  user_mongodb_data:
  media_mongodb_data:
  product_mongodb_data:
