services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: jenkins-controller
    restart: unless-stopped

    ports:
      - "8090:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /run/user/67984/podman/podman.sock:/var/run/docker.sock

    user: root

volumes:
  jenkins_home: