services:
  # -------------------------------------------------------------
  # USER MONGODB
  # -------------------------------------------------------------
  user-db:
    image: mongo:7.0
    container_name: mongodb_user
    restart: always
    env_file:
      - ../../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${USER_MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - user_mongodb_data:/data/db
volumes:
  user_mongodb_data:
